export const LEFT_PAGE_CONTROL_ENTHUSIASM = 'LEFT_PAGE_CONTROL_ENTHUSIASM';
export type LEFT_PAGE_CONTROL_ENTHUSIASM = typeof LEFT_PAGE_CONTROL_ENTHUSIASM;

export const RIGHT_PAGE_CONTROL_ENTHUSIASM = 'RIGHT_PAGE_CONTROL_ENTHUSIASM';
export type RIGHT_PAGE_CONTROL_ENTHUSIASM = typeof RIGHT_PAGE_CONTROL_ENTHUSIASM;

export const TOP_INPUT = 'TOP_INPUT';
export type TOP_INPUT = typeof TOP_INPUT;

export const GET_IP_DATA = 'GET_IP_DATA';
export type GET_IP_DATA = typeof GET_IP_DATA;

export const GET_STAR_ARTICLES = 'GET_STAR_ARTICLES';
export type GET_STAR_ARTICLES = typeof GET_STAR_ARTICLES;